### ISSUE TITLE
Use API level 17 (or lower)

### ISSUE THREAD

**Issue by wvengen** [n76/wifi_backend#2]
I've compiled and tested with API level 17 on an Android 4.2 device, and it seems to work without a problem.

**Comment by bharat226g** [comment]
On my device with android 4.2 , the backend gets installed and maps wifi AP's to gps locations. But the backend fails to provide location data to the system on Location request. Maps won't lock the network location with this backend within the range of mapped APs . 

Since UnifiedNlp has a legacy version supporting even android 2.3 , it would be ideal for this to support since android 2.3 . On devices below kitkat where background scanning isn't available, maybe a legacy version of app or by some other way it needs to support.
