### ISSUE TITLE
Seed database with public data

### ISSUE THREAD

**Issue by wvengen** [n76/wifi_backend#3]
Thanks for this great app! I've been wanting to look into writing such a thing, and it's a gift to find it here.

There's a feature I have in mind - seeding the database with public AP data. I haven't thought this through completely yet, but as a first step I'm thinking of either
* existing datasets by area, allow the user to select one or more, and import from the remote location (could be hosted at github.io), or
* an online database where we gather all public APs from existing services, and allow the UI to select coordinates (current GPS position) and a range (in km/miles). The service would then return the APs within range, and the app would import them.

Both would require some scripts to keep the datasets updated, but I'd be happy to look into that. Both would require some UI to ask the user what to download. When the datasource is stored in the local db as well, this would allow updating as a later improvement.

Known services with open AP-position data:
* [openwlanmap](http://openwlanmap.org/) - bssid, lon, lat ([GFDL](http://openwlanmap.org/LICENSE.txt))
* [openbmap](http://openbmap.org/) - raw observations incl. bssid, lon, lat ([ODbL](http://openbmap.org/openBmap-wifi-odbl-10.txt))

Is there any interest in such a feature? Does it belong here or in another app (if possible at all)?

**Comment by wvengen** [comment]
Ah, now I see the CSV import option in Local-GSM-Backend. I'll look into making pre-built downloads for that first. I guess focusing on GSM first makes sense. Feel free to close this issue for now.

**Comment by n76** [comment]
Okay. Feel to reopen in the future.

**Comment by Lee-Carre** [comment]
> seeding the database with public AP data

Since, as mentioned, there are other backends for using pre-loaded data, this being implemented here would, I feel, detract from the merits of this backend.

Personally, I really like that it's completely autonomous (no network access, completely offline) & takes a zero-(prior-)knowledge (starting from scratch) approach.

Why would I want lots of data about the rest of the world? For context, I'm on a small island, so only care about local data. I prefer having a tailored DB which is relevant to where I want to get offline positioning.
Small & efficient.

If I travel to other places, then the backend will collect the data it needs anyway.

Else, I'll use other backends alongside this, as needed or I see fit.
I strongly prefer the modular approach; build more complex systems out of well-defined components. Rather than expecting a single tool to do everything. The more general purpose something is, the less good it is in each area.
Or, as a French aircraft designer once put it (translated) ‘perfection is attained not when there is nothing more to add, but nothing more to take away’.
@n76 has very much followed that concept, here, and been lead to be novel & interesting approach to positioning.
