### ISSUE TITLE
import database doesn't work.

### ISSUE THREAD

**Issue by bharat226g** [n76/wifi_backend#32]
The export and import database functionality is great. But I never had import database working. Exporting the database creates wifi.json file. Then when tried to import, the wifi.json file is grayed out just like all other unimportant files. Tapping on that grayed out file does nothing. Please fix this.

**Comment by AreYouLoco** [comment]
I can also confirm that importing database of wifis never worked for me as well.

And this is quite handy option cuz after each update my database is getting clear again.

**Comment by n76** [comment]
My plan will be to add a CSV export/import capability.

The issue with the current JSON format is that import/export is by MIME type and, weirdly, Android does not have a file extension mapping defined for JSON. The result is only the exact file exported is remembered as having the correct MIME type, other files with a .json extension are not detected for import. It does have a mapping for CSV so that should work.

Even with a CSV file format there may be some issues with importing data from other sources in a useful manner: It seems to me that the best export method would emit the three saved perimeter location records for each AP and then on import treat each record as if detected by the scanning service (merge the data into whatever is existing). This will allow sharing data between instances of this backend on different phones as a minimum of three perimeter points will be imported for each AP. I think this would satisfy the desires expressed in https://github.com/n76/wifi_backend/issues/33

But locations of APs provided by other projects typically have only a single point, they would be merged in but since they don't contain the minimum number of samples to be used for location estimation would be ignored. One could pre-process that type of list to change the one center point into three perimeter points before import but I consider that beyond the scope of this backend.

**Comment by n76** [comment]
Import/export changed to a format that Android mime type mapping supports, so it should allow import of arbitrary CSV files (as long as the header line contains the fields "bssid", "lat", "lon" and optionally "ssid".
