### ISSUE TITLE
[feature request] Integrate with Wigle Wifi

### ISSUE THREAD

**Issue by RicoElectrico** [n76/wifi_backend#35]
It's a popular wardriving app, which saves observations to a sqlite database. Would be nice to use its local DB seamlessly as it grows. There are two tables, one with a single row per network, and second with all the observations ( >=1 per network).

**Comment by n76** [comment]
I am not sure makes sense for a number of reasons.

First, the backend is already sampling for WiFi APs so the locally collected data in the Wigle WiFi app would be redundant.

Second, on app on Android can't just access the database(s) or file(s) owned by another app. The Wigle App would need to provide a service that could be queried for the wifi data. It might do that, but I did not see mention when looking at their web site.

Third, the algorithm for estimating WiFI AP location is different, so the data collected is a bit different. Wigle says on their website that they use signal weighted centroiding (which appears to be pretty standard). That requires an estimate of signal strength and by its nature collects samples for an AP even where the location of that AP pretty well known. The [algorithm used by this backend](http://retiredtechie.fitchfamily.org/2014/12/13/bread-crumbs/) attempts to find the edge of the coverage area rather than the center.

This grew out of an experiment of mine to see, for privacy reasons, if it was possible to limit the amount of data collected and not “over report” data for your house, your work, where you shop, etc. and the typical way that you go between those places. If a project comes along that uses this algorithm then the export/import feature of this backend could be used to share data with that project.

**Comment by RicoElectrico** [comment]
> Wigle says on their website that they use signal weighted centroiding (which appears to be pretty standard).
The internet backend, not the app (which does collect multiple locations).
> Second, on app on Android can't just access the database(s) or file(s) owned by another app.
It's done the old-fashioned way, storing data at /sdcard/wiglewifi, if a file manager can access it, every app could.
