### ISSUE TITLE
What about "_nomap" SSIDs ?

### ISSUE THREAD

**Issue by breversa** [n76/wifi_backend#4]
Hi there,

I started using µg Unified NLP Provider last week (using the XposedUnifiedNlp module since I also have GApps installed) and set up both your GSM and wifi backends.

I also use Mozstumbler from time to time, and I read about their "_nomap" opt-out mechanism here : https://location.services.mozilla.com/optout

My question is : how does Local WiFi Backend handle SSIDs that end in "_nomap" ? Are they stored ? Are they discarded ? Maybe only store "_nomap" SSIDs that I'm actullay connected to (such as my own) ?

**Comment by n76** [comment]
At present APs with names ending in "_nomap" are immediately discarded, see WiFiSamplerService.java around line 196. There is a need to avoid using APs that are likely to be mobile when estimating location. That is done in several ways:

1. Ignore APs with names that contain things like "_nomap" or "iphone".

2. Detect APs that have an implausibly large coverage radius. These are marked as "moved" and have to remain in their new location for a fairly long period of time before they are trusted again.

3. Only use groups of plausibly close APs when doing location calculation. Unfortunately that also means that if only one AP is in range, no location is returned.

Data collected by the phone is anonymized (no SSID is stored) and there is no facility for exporting or sharing the data. So I think one of the reasons people add a "_nomap" suffix (privacy) is avoided so I am not sure that I really need to ignore it but I do.

**Comment by breversa** [comment]
Thanks for the detailed answer. :-)

What about hidden SSID that I can connect to ? Are they ignored or not ?
I was actually wondering if my own hidden and _nomap wifi AP could do any good to better locate my devices. ^^ From what you say, the answer is no because of _nomap.

What if everybody added _nomap to their AP SSID ? They would all be ignored and Local Wifi Backend would serve no purpose. Whereas if _nomap SSID that I can connect to were accounted for, that'd be better already, no ?

**Comment by breversa** [comment]
(The above question "What if everybody added _nomap to their AP SSID ?" actually means "what if SSID-mapping gets ruled as opt-in instead of opt-out" in the future)

**Comment by n76** [comment]
APs that do not announce their SSIDs are added to the local database regardless if you can connect to them or not.

The main issue I am worried about is polluting the database with APs located on trams, buses or even an individual walking or driving around with their cell phone set to provide a local hotspot. From observation, some of those are obvious: Apple devices seem to have "iphone" or "ipad" somewhere in the SSID. Some Samsung phones have either "Samsung" or "Galaxy" or both in the SSID. But others seem to have totally innocuous names which leads me to think that filtering out APs by SSID to avoid ones that might move is not possible in the general case. So I am considering dropping that filter altogether.

As I don't think there is a privacy issue with this backend, I am seriously considering including _nomap SSIDs in the local database. Even if I continue to ignore SSIDs with strings containing things like "iphone".

Unlike a publicly accessible database where some one who inexplicably knew your WiFi MAC address could look up your location, I don't see a privacy issue with this backend. I don't provide a way to examine or share the collected data. And to provide a location at least two WiFi APs with known positions are required. I welcome your thoughts on this.

**Comment by breversa** [comment]
Trying to maintain a list of mobile SSIDs might be both a hassle and not necessarily sound, unless kept to the obvious minimum maybe ("iphone", "AndroidAP", etc.).

But come to think of it, Network Discovery (https://github.com/rorist/android-network-discovery) uses a database of NICs (based on the MAC addresse, I suppose). Would it be possible to discard APs according to their NIC rather than their SSID, maybe ?

**Comment by n76** [comment]
It looks like network discovery downloads and parses a file from http://standards.ieee.org/regauth/oui/oui.txt and then uses the first three octets to of the MAC address determine device manufacturer.

Using the first bit of the MAC address is probably better than using SSID but still has issues. For example, 00-0D-AE is for Samsung and is what my phone uses. But they also make other products that are likely to be stationary and I don't see another Samsung entry so it is possible that those other devices use the same first octets. Apple has a number of MAC address prefixes assigned and I don't see a difference in range on the Apple products we have at home between mobile devices and desktops. They make so many products that maybe it is a function of when the device was made rather than what type of device it is.

And devices that one might normally think as stationary like a printer, could be mounted in a service vehicle and be run off of an inverter. So I think some sort of moved/mobile detection logic needs to be maintained regardless if one discards APs by SSID or MAC address. And if that logic is good enough then it shouldn't matter what the name or address is.

Still some types of devices (Apple and Samsung) are more likely to move around than others (Cisco) so the idea has merit as a way to hint at whether or not the device is likely to move around.

**Comment by Lee-Carre** [comment]
> But others seem to have totally innocuous names which leads me to think that filtering out APs by SSID to avoid ones that might move is not possible in the general case. So I am considering dropping that filter altogether.

I think that there is value in excluding SSIDs which are known to be non-stationary, even if that filtering is imperfect. It reduces the noise (and DB bloat). Less processing by the backend, to deal with roaming ones, which keeps power-use low.

Besides, you've already implemented the feature (time & effort), which continues to function well; why remove it? 😉

Other collecting apps also implement similar blacklists, so there's clearly value in it.

**Comment by Lee-Carre** [comment]
@n76

> As I don't think there is a privacy issue with this backend, I am seriously considering including `_nomap` SSIDs in the local database. Even if I continue to ignore SSIDs with strings containing things like "iphone".

> Unlike a publicly accessible database where some one who inexplicably knew your WiFi MAC address could look up your location, I don't see a privacy issue with this backend. I don't provide a way to examine or share the collected data. And to provide a location at least two WiFi APs with known positions are required. I welcome your thoughts on this.

I think it better to continue to exclude such SSIDs.

If someone has gone to the trouble of learning how to opt-out, and reconfiguring their SSID, then they must really want to remain uncaptured.
As someone who values my own privacy, I'm strongly inclined to reciprocate.

Since an export function is now implemented, then it's even easier to (inadvertently) publish a dataset which includes `_nomap`.

Even without a specific function, it's still possible to extract the database via `adb`.

In my experience, few if any SSIDs (that I've observed) include the opt-out suffix. If, instead, it were commonly added by default, then that might be different.

**Comment by gdt** [comment]
I am conflicted.   To me, the point of nomap is a request not to publish, not a request not to remember.  But remembering leads to leaks.   So I do lean to not recording them.   However, two points:

   I would like to learn networks I am authorized to join, even if nomap.  So basically mark a nomap ssid as acceptable if we are observed joined to it.

   the export function, if any, could omit nomap ssids

   add an opt-in to mark an ssid as learnable, perhaps the currently-connected ssid only.
