### ISSUE TITLE
A mapping feature would be great

### ISSUE THREAD

**Issue by catFreeAndroid** [n76/wifi_backend#41]
First of all, let me just say that I love this app, It’s like a GPS cache!

For some reason whenever I’m not in a hurry and know I’m going to some place I’ve never been while using this app, I enable OsmAnd “trip recording” that keeps the GPS running in the background so that the wifi backend can keep running and mapping. After a while I gather a lot of unnecessary gpx files, not to mention the high battery consumption.

Is it possible to implement this feature in the backend itself, removing any unnecessary logging and improving battery life?

And why aren’t RSSI values logged? Why not log only the point that has the strongest signal and acceptable GPS error in conjunction with the point that is further way from the strongest signal point and has acceptable GPS error. My idea is to assume the strongest point as the center of the AP and using the weakest point distance from strongest point as the radius/range.

**Comment by n76** [comment]
A big issue with turning on the GPS in the backend is that the controls are difficult to get to (open microG app, select backends, select this backend before getting to the first possible place to put a GPS control). So turning GPS on and off would be a pain. And you don't want to leave the GPS on because it is a big battery drain.

An easy way to have the GPS on in the background is to run [OsmTracker](https://f-droid.org/repository/browse/?fdfilter=osm&fdid=me.guillaumin.android.osmtracker). And when you arrive where ever you were going, stop recording and delete the track instead of exporting it. Similar to what you are doing in OsmAnd but without wasting space with track files. You can even put the phone to sleep and it will still record the data. I do this when walking or bicycling. For longer trips you'll want to have the phone plugged into a power supply as the GPS does use a fair amount of power.

Since it does not matter what application turns on the GPS, you could write one that simply did that and then sat in the background throwing away the data. Bring it to the foreground and have an exit button implemented to stop the background GPS. I guess I could do that, but I don't mind having the screen on when in the car so usually run [OsmAnd](https://f-droid.org/repository/browse/?fdfilter=osmand&fdid=net.osmand.plus), [Maps.me](https://play.google.com/store/apps/details?id=com.mapswithme.maps.pro) or [SatStat](https://f-droid.org/repository/browse/?fdfilter=SatStat&fdid=com.vonglasow.michael.satstat) when I am driving around.

Regarding the algorithm, if all you are trying to detect is the edge of coverage then you don't need to record RSSI so I don't. The RSSI is used in computed the estimated location but that is a whole different operation.

If you wanted to reduce the storage (only store the point with max RSSI and an estimate of range), then you more likely to get more accurate AP location estimates by using a couple state variables for each AP and build a RSSI weighted geometric mean and variance where the variance would give you an estimate of the coverage range. The issue with that is privacy: Schemes that do this collect more data in places you frequent than in places you visit less often so you can look for the places with high sample counts to get information about where the person has been.

The algorithm I use was originally arrived at with the concept of sharing WLAN/WiFi AP location data while minimizing leakage of personal information about where you live, work, shop, play, etc. I haven't updated it in a while, but I [blogged the concept](http://retiredtechie.fitchfamily.org/2014/12/13/bread-crumbs/) around the time I started working on this backend.

The current version of the backend can export (share) all data or just the changes since the last export. This feature relies on the three sample point concept and I plan to eventually write some web server side code (open source) to use this type of export data to allow one to share. Actually you can share now by exporting the changes, sending the changed data file(s) to who ever you want and have them import the files into their copy of the backend: The import does a merge of the file data and what is in the database.

**Comment by Lee-Carre** [comment]
> An easy way to have the GPS on in the background is to run [OsmTracker](//f-droid.org/repository/browse/?fdfilter=osm&fdid=me.guillaumin.android.osmtracker). And when you arrive where ever you were going, stop recording and delete the track

Even easier is (from [n76/DejaVu#25 (comment)](//github.com/n76/DejaVu/issues/25#issuecomment-1040310105)):
> There are apps which have a feature to toggle GNSS on (and keep it enabled), without doing much more (low memory usage).
> * [OpenTracks](//www.f-droid.org/packages/de.dennisguse.opentracks) (`Start G[NS]S`, which is distinct from starting to record a track)
> * [My Location](//www.f-droid.org/packages/com.mirfatif.mylocation) (`Lock G[NS]S`) (has other useful features, including the ability to query UnifiedNLP backends)
> 
> I use such an app when I'm out, for a whole variety of reasons (besides for n76's backends to collect data, also other data-collectors (e.g. Tower Collector), [map](//www.openstreetmap.org/) surveying, and not having to wait for GNSS to stabilise when I want to use various (e.g. navigation) apps).
> 
> However, I also use an external battery, so the extra power usage isn't a concern for me. It might be for others.
