### ISSUE TITLE
Easy feature request: reset database

### ISSUE THREAD

**Issue by demecoandrea** [n76/wifi_backend#44]
I know that this is strange but I delete the known APs database frequently.
I have to go into the android setting, and manually clear the app data.

Would it be possible to add a simple "Delete database" button inside in the app itself instead of the raw "clear data"?

I would be very grateful! (Actually I should say "I would be even more grateful" XD I'm using this backend every day since about 2 year and I have to say THANK YOU, and GOD BLESS YOU for this beautiful app, I'm already grateful :)

**Comment by ArchangeGabriel** [comment]
I’m also in need for this feature. Basically, I travel a lot and generally purge the DB when moving away in order to avoid storage of millions of data points. Then I reimport the exported DB of my usual places (home(s), work(s), etc.). But doing so requires me to go into the Android settings and remove the data, which also remove the permission (annoying but very easy to manage) and the backend settings (annoying too, need to reinput the value by hand).
